apiVersion: v1
kind: Pod
metadata:
  name: root-pod
spec:
  containers:
  - name: my-container
    image: busybox
    resources:
      requests:
        cpu: 100m
    securityContext:
      runAsUser: 0
    command: ["sh", "-c", "echo 'Hello, Kubernetes!' >> /var/hello.txt"]
