apiVersion: v1
kind: Pod
metadata:
  name: root-pod
  namespace: kube-system
spec:
  containers:
  - name: my-container
    image: busybox
    resources:
      limits:
        cpu: 100m
    securityContext:
      runAsUser: 0
    command: ["sh", "-c", "echo 'Hello, Kubernetes!' >> /var/hello.txt"]
