apiVersion: v1
kind: Pod
metadata:
  name: root-pod
  namespace: acceptance-tests
spec:
  containers:
  - name: my-container
    image: busybox
    resources:
      limits:
        cpu: 100m
    command: ["sh", "-c", "echo 'Hello, Kubernetes!' >> /var/hello.txt"]
